# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'KaizenGamingChallenge' do
  use_frameworks!
  pod 'Alamofire', '5.9.1'

  target 'KaizenGamingChallengeTests' do
    inherit! :search_paths
    pod 'Alamofire', '5.9.1'
  end

end
