# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'KaizenGamingChallenge' do
  use_frameworks!
  pod 'Alamofire', '5.9.1'
  pod 'SwiftLint', '0.55.1'

  target 'KaizenGamingChallengeTests' do
    inherit! :search_paths
    pod 'Alamofire', '5.9.1'
    pod 'SwiftLint', '0.55.1'
  end

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
    end
  end
end